name: Deploy Content to Dev
on:
  push:
    branches:
      - CI
  workflow_dispatch:
  
permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: dev
    name: 'Terraform LearningHub Content Server'
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false  # Skip wrapper script installation

      - name: 'Terraform init'
        id: init
        run: |
          terraform init "-backend-config=backend-dev.tfvars"

      # One time stuff to do the initial terraform import

      # - name: 'Terraform import resource group'
      #   run: |
      #     terraform import azurerm_resource_group.ContentServerResourceGroup /subscriptions/66516f71-f3d4-4911-b900-c6e4690a5b15/resourceGroups/UKS-LearningHub-ContentServer-DEV-RG
      #     terraform import azurerm_app_service_plan.ContentServerAppServicePlan /subscriptions/66516f71-f3d4-4911-b900-c6e4690a5b15/resourceGroups/UKS-LearningHub-ContentServer-DEV-RG/providers/Microsoft.Web/serverFarms/learninghub-content-dev-plan
      #     terraform import azurerm_app_service.ContentServerAppService /subscriptions/66516f71-f3d4-4911-b900-c6e4690a5b15/resourceGroups/UKS-LearningHub-ContentServer-DEV-RG/providers/Microsoft.Web/sites/learninghub-content-dev
 
      # End of one time stuff

      - name: 'Terraform apply'
        run: |
          terraform apply -auto-approve \
            -var="ResourceGroupName=${{ vars.AZURE_RESOURCE_GROUP_NAME }}" \
            -var="ResourceGroupLocation=${{ vars.AZURE_RESOURCE_GROUP_LOCATION }}" \
            -var="AppServicePlanName=${{ vars.AZURE_APP_SERVICE_PLAN_NAME }}" \
            -var="AppServicePlanKind=${{ vars.AZURE_APP_SERVICE_PLAN_KIND }}" \
            -var="AppServicePlanSkuTier=${{ vars.AZURE_APP_SERVICE_PLAN_SKU_TIER }}" \
            -var="AppServicePlanSkuSize=${{ vars.AZURE_APP_SERVICE_PLAN_SKU_SIZE }}" \
            -var="AppServiceName=${{ vars.AZURE_APP_SERVICE_NAME }}"

  deploy_content_server:
    runs-on: ubuntu-latest
    environment: dev
    name: 'Deploy content server to app service'
    env:
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}

    steps:
      - uses: actions/checkout@v2
      
      - name: Add Azure artifact
        run: dotnet nuget add source 'https://pkgs.dev.azure.com/e-LfH/_packaging/LearningHubFeed/nuget/v3/index.json' --name 'LearningHubFeed'  --username 'kevin.whittaker' --password ${{ secrets.AZURE_DEVOPS_PAT }} --store-password-in-clear-text

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1
        with:
          nuget-version: '5.8.0'

      - name: Restore NuGet packages
        run: nuget restore ${{ env.Solution || 'LearningHub.Nhs.Content.sln' }}

      # - name: Setup MSBuild
      #   uses: microsoft/setup-msbuild@v1.1

      # - name: Build solution
      #   run: msbuild LearningHub.Nhs.Content.sln /p:Configuration=${{ env.BuildConfiguration }} /p:Platform="${{ env.BuildPlatform }}" /p:OutDir="${{ github.workspace }}\artifact"
  
      # - name: 'Az CLI login'
      #   uses: azure/login@v1
      #   with:
      #     client-id: ${{ secrets.AZURE_CLIENT_ID }}
      #     tenant-id: ${{ secrets.AZURE_TENANT_ID }}
      #     subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Build project
        run: npm run build

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .

